export const ADD_ALERT = "ADD_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOAD_PATIENT = "LOAD_PATIENT";
export const LOGIN_SUCCESS_PATIENT = "LOGIN_SUCCESS_PATIENT";
export const LOGIN_FAIL_PATIENT = "LOGIN_FAIL_PATIENT";
export const REGISTER_SUCCESS_PATIENT = "REGISTER_SUCCESS_PATIENT";
export const REGISTER_FAIL_PATIENT = "REGISTER_FAIL_PATIENT";
