export const ADD_ALERT = "ADD_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOAD_USER = "LOAD_USER";
export const LOGIN_SUCCESS_USER = "LOGIN_SUCCESS_USER";
export const LOGIN_FAIL_USER = "LOGIN_FAIL_USER";
export const REGISTER_SUCCESS_USER = "REGISTER_SUCCESS_USER";
export const REGISTER_FAIL_USER = "REGISTER_FAIL_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_APPOINTMENT_CONSULTATION = "ADD_APPOINTMENT_CONSULTATION";
export const REMOVE_APPOINTMENT_CONSULTATION = "REMOVE_APPOINTMENT_CONSULTATION";
export const LOAD_APPOINTMENT_CONSULTATIONS = "LOAD_APPOINTMENT_CONSULTATIONS";
export const FINISH_APPOINTMENT_CONSULTATION = "FINISH_APPOINTMENT_CONSULTATION";
export const CANCEL_APPOINTMENT_CONSULTATION = "CANCEL_APPOINTEMENT_CONSULTATION";

export const LOAD_DOCTOR = "LOAD_DOCTOR";
export const LOGIN_SUCCESS_DOCTOR = "LOGIN_SUCCESS_DOCTOR";
export const LOGIN_FAIL_DOCTOR = "LOGIN_FAIL_DOCTOR";
export const LOGOUT_DOCTOR = "LOGOUT_DOCTOR";

export const LOAD_ADMIN = "LOAD_ADMIN";
export const LOGIN_SUCCESS_ADMIN = "LOGIN_SUCCESS_ADMIN";
export const LOGIN_FAIL_ADMIN = "LOGIN_FAIL_ADMIN";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
export const ADD_SPECIALIZATION = "ADD_SPECIALIZATION";
export const LOAD_SPECIALIZATIONS = "LOAD_SPECIALIZATIONS";
export const REMOVE_SPECIALIZATION = "REMOVE_SPECIALIZATION";
export const EDIT_SPECIALIZATION = "EDIT_SPECIALIZATION";
export const LOAD_DOCTORS = "LOAD_DOCTORS";
export const REMOVE_DOCTOR = "REMOVE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const LOAD_USERS = "LOAD_USERS";
export const REMOVE_USER = "REMOVE_USER";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const LOAD_MESSAGE = "LOAD_MESSAGE";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const MARK_READ_MESSAGE = "MARK_READ_MESSAGE";

export const LOAD_USERS_DATA = "LOAD_USERS_DATA";
export const LOAD_DOCTORS_DATA = "LOAD_DOCTORS_DATA";
export const LOAD_SPECIALIZATIONS_DATA = "LOAD_SPECIALIZATIONS_DATA";